spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/hai-chat?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
server:
  port: 9999
  servlet:
    context-path: /api
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.hblolj.haichat.dataobject
